services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: hello
    ports: ["5432:5432"]
  api:
    build: .
    environment:
      DATABASE_URL: postgres://hello:hello@db:5432/hello
    ports: ["8080:8080"]
    depends_on: [db]